name: Feature Request
description: Suggest an improvement to templates, specs, or tooling
labels: ["enhancement"]
body:
  - type: dropdown
    id: area
    attributes:
      label: What area does this relate to?
      options:
        - Template files (root .txt / .json / .html)
        - Specifications (specs/)
        - Validation / tooling
        - Documentation
        - Examples
        - New file type proposal
        - Other
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: What would you like to see?
      description: Describe the improvement or new feature.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Why is this useful?
      description: How would this help people implementing AI Discovery Files?
    validations:
      required: false
